Building on triassic08 (Linux).

diff --git a/tests/hertz/Makefile b/tests/hertz/Makefile
--- a/tests/hertz/Makefile
+++ b/tests/hertz/Makefile
@@ -8,13 +8,33 @@ override INCLUDEDIR += -I ../../../inc -I ../../common
 # COMMON LIBS
 override LIB = -L../../../lib -lclwrapper -lscan -lgpunl -lcommon
 
+# OPENCL LIBRARIES BASED ON OS
+UNAME := $(shell uname)
+ifeq ($(UNAME), Darwin)
+OPENCL_LIB = -framework OpenCL
+OPENCL_INC =
+SHARED = -dynamiclib
+endif
+
+ifeq ($(UNAME), Linux)
+.PHONY: .check-env
+AMDAPP ?= /opt/AMDAPP/include
+.check-env:
+	@if [ ! -d "${AMDAPP}" ]; then \
+		echo "ERROR: set AMDAPP variable."; exit 1; \
+	fi
+OPENCL_LIB = -l OpenCL 
+OPENCL_INC = -I ${AMDAPP}
+SHARED = -shared
+endif
+
 %.o: %.cpp
-	$(CXX) $(CXXFLAGS) $(INCLUDEDIR) -c -o $@ $<
+	$(CXX) $(CXXFLAGS) $(INCLUDEDIR) $(OPENCL_INC) -c -o $@ $<
 
 OBJS = hertz_gpuneighlist.o	hertz_wrapper.o
 
 driver: driver.cpp $(OBJS)
-	$(CXX) $(CXXFLAGS) $(INCLUDEDIR) -o $@ $^ $(LIB)
+	$(CXX) $(CXXFLAGS) $(INCLUDEDIR) $(OPENCL_INC) -o $@ $^ $(LIB) $(OPENCL_LIB)
 
 hertz_gpuneighlist.cpp hertz_wrapper.cpp:
 	../../pairgen.py hertz.yml
